### ISSUE TITLE
Issue to deploy the docker-compose file

### ISSUE THREAD

**Issue by darrepac** [lomorage/lomo-docker#15]
Hello

Here is the docker-compose file that I use which comes from here:
```
version: "3.9"
services:
  lomo:
    image: lomorage/amd64-lomorage:latest
    container_name: lomorage
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /NEWNAS/DOWNLOADS/Lomorage:/media/primary
#      - ${HOME_MEDIA_BAKUP_DIR}:/media/backup
      - /srv/dev-disk-by-uuid-3113b027-5b78-45ff-8658-55185af89df2/CONFIG/Lomorage_cfg:/lomo
      - /dev:/dev
    ports:
      - 8001:8001
    networks:
      lomorage:
        ipv4_address: 192.168.0.57
    command: 8001

  watchtower:
    image: containrrr/watchtower:amd64-latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: lomorage --cleanup

networks:
  lomorage:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
```

And I got the following error:
`Deployment error
failed to deploy a stack: The Compose file '/data/compose/24/docker-compose.yml' is invalid because: services.lomo.command contains an invalid type, it should be a string, or an array : exit status 1`
